# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 30c89172a63d5a0ddd10580424cff25c96cc95f9d37bf2fe958a3c725a225e9b9337df4692752fe09774799efcbadda38b9ce17b99fb62d13f57618c19389adb

test:
  secret_key_base: efab4327be47a3f6c5b7400da0aeae1a7afcbe7659686a49f6d034e25d9eeb13416cc2351e83f7c2310188a8ccfbc2d8fbfb5ced2bd2236cca22e7966571523a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
